version: "3.9"
services:
    web:
        build: .
        command: ./docker-entrypoint.dev.sh
        ports:
            - 8000:8000
        depends_on:
            - db
            - redis
        restart: always
        env_file:
            - .env
        volumes:
            - .:/app

    db:
        image: postgres:14.1-alpine
        restart: always
        ports:
            - "5432:5432"
        env_file:
            - .env
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB_URL=${DATABASE_URL}

    redis:
        image: redis:6.2-alpine
        ports:
            - 6379:6379
        restart: always
        volumes:
            - redisdata:/data
        env_file:
            - .env

volumes:
    pgdata:
    redisdata:
