# Generated by Django 4.2.13 on 2024-05-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_conversation_message_messageviewers_message_seen_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_sent",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="conversationmembers",
            name="joined_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
