# Generated by Django 4.2.13 on 2024-05-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_message_is_sent_alter_conversation_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
