name: Run tests

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Generate .env file
              uses: SpicyPizza/create-envfile@v1.3
              with:
                  envkey_DEBUG: ${{ secrets.DEBUG }}
                  envkey_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
                  envkey_DJANGO_CSRF_TRUSTED_ORIGINS: ${{ secrets.DJANGO_CSRF_TRUSTED_ORIGINS }}
                  envkey_TIME_ZONE: ${{ secrets.TIME_ZONE }}
                  envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  envkey_CHANNEL_LAYERS_BACKEND: ${{ secrets.CHANNEL_LAYERS_BACKEND }}
                  envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  envkey_REDIS_HOST: ${{ secrets.REDIS_HOST }}
                  envkey_REDIS_PORT: ${{ secrets.REDIS_PORT }}
                  envkey_REDIS_CACHE_URL: ${{ secrets.REDIS_CACHE_URL }}
                  envkey_DJANGO_LOG_LEVEL: ${{ secrets.DJANGO_LOG_LEVEL }}
                  envkey_MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
                  envkey_SENTRY_URL: ${{ secrets.SENTRY_URL }}
                  file_name: .env
                  fail_on_empty: false

            - name: Set up Docker Compose
              run: |
                  sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                  sudo chmod +x /usr/local/bin/docker-compose

            - name: Build the Docker containers
              run: docker-compose -f docker-compose.dev.yml up -d --build --remove-orphans

            - name: Make run_tests.sh executable
              run: chmod +x ./app/run_tests.sh

            - name: Run tests
              run: docker-compose -f docker-compose.dev.yml exec web ./run_tests.sh
