name: Run tests

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Generate .env file
              uses: SpicyPizza/create-envfile@v1.3
              with:
                  envkey_DEBUG: ${{ secrets.DEBUG }}
                  envkey_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
                  envkey_DJANGO_CSRF_TRUSTED_ORIGINS: ${{ secrets.DJANGO_CSRF_TRUSTED_ORIGINS }}
                  envkey_TIME_ZONE: ${{ secrets.TIME_ZONE }}
                  envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  envkey_DB_NAME: ${{ secrets.DB_NAME }}
                  envkey_DB_PASS: ${{ secrets.DB_PASS }}
                  envkey_DB_USERNAME: ${{ secrets.DB_USERNAME }}
                  envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  envkey_REDIS_HOST: ${{ secrets.REDIS_HOST }}
                  envkey_REDIS_PORT: ${{ secrets.REDIS_PORT }}
                  envkey_REDIS_CACHE_URL: ${{ secrets.REDIS_CACHE_URL }}
                  envkey_DJANGO_LOG_LEVEL: ${{ secrets.DJANGO_LOG_LEVEL }}
                  envkey_MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
                  envkey_SENTRY_URL: ${{ secrets.SENTRY_URL }}
                  file_name: .env
                  fail_on_empty: false

            - name: Set up Docker Compose
              run: |
                  sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                  sudo chmod +x /usr/local/bin/docker-compose

            - name: Log .env file
              run: cat .env

            - name: Build the Docker containers
              run: docker-compose -f docker-compose.dev.yml up -d --build --remove-orphans

            - name: List all running containers
              run: docker ps -a

            - name: Print DB logs
              run: docker-compose -f docker-compose.dev.yml logs db

            - name: Wait for DB to be ready
              run: |
                  docker-compose -f docker-compose.dev.yml run web sh -c 'until nc -z db 5432; do echo "Waiting for db"; sleep 3; done'

            - name: List all running containers
              run: docker ps -a

            - name: Make run_tests.sh executable
              run: chmod +x run_tests.sh

            - name: Run tests
              run: docker-compose -f docker-compose.dev.yml run web ./run_tests.sh
